### PR TITLE
Allow including / excluding particular files when watching directory

### PR DESCRIPTION
**Pull request by freizl**
1. use optparse-applicative to parse parameters.
2. allow to include / exclude paricular files via regex.

### CODE REVIEW

**Comment by ehamberg** [comment]
This looks great. However, it would be good if these were split over several commits (and possibly even several pull requests). From a quick glance I see the following changes:

1. Move source files to `src`
2. Build with stack (i.e. adding `stack.yaml` and ignoring `.stack-work`)
3. Changing parameter parsing to use `optparse-applicative`
4. Allow including/excluding some patterns (depends on the previous change)
5. Bumping the version number

Maybe some of them could be combined, but this should definitely be more than one commit. Especially the moving of the source file makes it hard to read the diff and see what changed.

If you could update the pull request – or create a new one – with one commit per change, I'd love to merge this. Let me know if you would like any help with this. :)

**Comment by freizl** [comment]
I have combined 3, 4, 5 as that's my major goal. I think it's making little sense by splitting 3 and 4.
Hopefully it looks good to you.

The changes include stylish "import" by `stylish-haskell`. I could remove them if you don't like.

**Comment by ehamberg** [comment]
Hi. Thanks for getting back to me.

This new commit does three things:

1. Use optparse-applicative
2. Allow exluding files/dirs
3. Changes `import` statements to use *stylish-haskell* style

If you feel that it makes little sense splitting the first two, that's fine. However, then that's one commit, with a unified title. As of now the title line of the commit is “1. use optparse-applicative […]”. Git commit messages should be in the format

    Title summarizing the whole commit
    
    More description.

(Note the empty line between the title and the more detailed description.)

In this case the title should be something like “Allow excluding file patterns” and the description should be where you explain what was actually done, e.g.:

    1. use optparse-applicative to parse parameters.
    2. allow to include / exclude paricular file patterns.

I really don't want to sound ungrateful and super-picky, but this is how git is usually used (one commit per change) and the format of commit messages (short title summarizing changes, empty line, description) is described in `man git-commit` under *Disussion* [1]. By following this format you make sure that tools such as github and `git log --oneline` still work and show the title of the commit. :)

The style change of `import` statements should be a commit on its own since it's not related to the other changes.

(Again, I'm happy to assist with git help if needed. Looks like a great contribution!)

[1] <https://www.kernel.org/pub/software/scm/git/docs/git-commit.html>

**Comment by freizl** [comment]
Thanks much your suggestions. I shall make it at first place.

I prefer the style that small changes per commit. 
However one PR per one commit seems little tedious? (Especially when changes are simple.)

**Comment by ehamberg** [comment]
Thank you very much! Sorry for keeping you waiting. Real-life suddenly intervened. :)

I don't really suggest one PR per commit, but one PR per issue. The problem with a PR that does X, Y and Z is that Y might, e.g. be a style change that isn't necessary and suddenly the person who reviews the pull request need to consider whether this is something that s/he wants instead of focusing on the X and Z commits that are great and could be merged immediately. :)

Of course, it isn't always black and white, and it isn't always completely clear what belongs together, but the overhead of creating commits and pull requests with git/github is really low, and greatly increases the chance of a request being quickly accepted.

Any way… thank you so much for the great contribution. Sorry for talking a hole in your head. ;)

**Comment by freizl** [comment]
Thank you!

**Pull request merged**
