### PR TITLE
Ignore directory indicator for `Event`s with fsnotify >= 0.3

### LINKED ISSUE #8: Build failure with ghc-8.4.2
```
Failed to build fswatcher-0.2.1.
Build log (
/home/simon/.cabal/logs/ghc-8.4.2/fswatcher-0.2.1-d7a5f09ca4df464cda6585553e273af58d6cf6be6512f3837d8ec690da63fc2b.log
):
Configuring fswatcher-0.2.1...
Preprocessing executable 'fswatcher' for fswatcher-0.2.1..
Building executable 'fswatcher' for fswatcher-0.2.1..
[1 of 3] Compiling Opts             ( Opts.hs, dist/build/fswatcher/fswatcher-tmp/Opts.o )
[2 of 3] Compiling Pipeline         ( Pipeline.hs, dist/build/fswatcher/fswatcher-tmp/Pipeline.o )
[3 of 3] Compiling Main             ( fswatcher.hs, dist/build/fswatcher/fswatcher-tmp/Main.o )

fswatcher.hs:39:21: error:
    • The constructor ‘Modified’ should have 3 arguments, but has been given 2
    • In the pattern: Modified p _
      In an equation for ‘isThisFile’:
          isThisFile (Modified p _) = p == fromString path
      In an equation for ‘watch’:
          watch filetype m path trigger opt
            = let watchFun = ...
              in watchFun (\ _ -> void $ tryPutMVar trigger ())
            where
                isThisFile (Modified p _) = p == fromString path
                isThisFile _ = False
                matchFiles :: WatchOpt -> Event -> Bool
                matchFiles wo event
                  = let ...
                    in
                      (null includes || p =~ includePath wo)
                        && (null excludes || not (p =~ excludePath wo))
   |
39 |   where isThisFile (Modified p _) = p == fromString path
   |                     ^^^^^^^^^^^^
cabal: Failed to build fswatcher-0.2.1. See the build log above for details.
```

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #8.

### CODE REVIEW

**Comment by ehamberg** [comment]
Thanks!

**Comment by sjakobi-as** [comment]
@ehamberg Can you please release this fix?

**Comment by ehamberg** [comment]
@sjakobi Done. Sorry for taking so long.

**Comment by sjakobi-as** [comment]
No worries. Cheers! :-)

**Pull request merged**
